/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/booking-history`; params?: Router.UnknownInputParams; } | { pathname: `/confirmation`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/payment`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/schedule`; params?: Router.UnknownInputParams; } | { pathname: `/select-pet`; params?: Router.UnknownInputParams; } | { pathname: `/select-service`; params?: Router.UnknownInputParams; } | { pathname: `/service-details`; params?: Router.UnknownInputParams; } | { pathname: `/success`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/booking-history`; params?: Router.UnknownOutputParams; } | { pathname: `/confirmation`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/payment`; params?: Router.UnknownOutputParams; } | { pathname: `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/schedule`; params?: Router.UnknownOutputParams; } | { pathname: `/select-pet`; params?: Router.UnknownOutputParams; } | { pathname: `/select-service`; params?: Router.UnknownOutputParams; } | { pathname: `/service-details`; params?: Router.UnknownOutputParams; } | { pathname: `/success`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/booking-history${`?${string}` | `#${string}` | ''}` | `/confirmation${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/payment${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `/schedule${`?${string}` | `#${string}` | ''}` | `/select-pet${`?${string}` | `#${string}` | ''}` | `/select-service${`?${string}` | `#${string}` | ''}` | `/service-details${`?${string}` | `#${string}` | ''}` | `/success${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/booking-history`; params?: Router.UnknownInputParams; } | { pathname: `/confirmation`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/payment`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/schedule`; params?: Router.UnknownInputParams; } | { pathname: `/select-pet`; params?: Router.UnknownInputParams; } | { pathname: `/select-service`; params?: Router.UnknownInputParams; } | { pathname: `/service-details`; params?: Router.UnknownInputParams; } | { pathname: `/success`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
